name: Prettier
on: [push]
jobs:
  checkformat:
    name: checkformat
    runs-on: ubuntu-latest
    steps:
      # Installs bun
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # Install deps and check formatting
      - run: bun install
      - run: bun checkformat
